# NumPy

#La API: Interfaz con la que un programa o una aplicación se conecta con otra aplicación.

#Cómo nos conectamos con otra aplicación a través de código. Se puede instalar desde Jupyter con un !conda install numpy desde el kernel de Ironhack. O, import numpy as np print(np.__version__) Para instalarlo en la terminal. conda activate (entorno Ironhack); conda activate numpy.


In [2]:
import numpy as np
print(np.__version__)

1.20.1


In [41]:
# primero crear un objeto, que en última instacia es una matriz. Objeto=n_d_array; Nombre métodos= matriz
n_d_array = np.array([[1,2,3], [4,5,6]]) # la ma

print(n_d_array, end='\n')

[[1 2 3]
 [4 5 6]]


In [42]:
print(n_d_array, end='\n\n')

[[1 2 3]
 [4 5 6]]



In [43]:
print(type(n_d_array))

<class 'numpy.ndarray'>


In [44]:
print(n_d_array.ndim) #.ndim es un atributo

2


In [45]:
print(n_d_array.shape) # forma

(2, 3)


In [46]:
print(n_d_array.size) # cantidad de elementos en la matriz

6


In [47]:
print(n_d_array.dtype) #int de que son integres

int32


In [48]:
print(n_d_array.itemsize) #tamaño en bytes

4


In [49]:
copy = n_d_array.copy()
copy


array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
py_list=n_d_array.tolist()
py_list

[[1, 2, 3], [4, 5, 6]]

In [51]:
reshaped = n_d_array.reshape(3,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
transposed = reshaped.transpose()
transposed

array([[1, 3, 5],
       [2, 4, 6]])

In [53]:
flattened = n_d_array.flatten()
flattened

array([1, 2, 3, 4, 5, 6])

In [55]:
max_ = n_d_array.max()
max_

6

In [56]:
argmax_= n_d_array.argmax() # Returns the indices of the maximum values along an axis
argmax_

5

In [57]:
sum_ = n_d_array.sum()
sum_

21

In [64]:
arry_range = np.arange(8)
arry_range

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
zero_array= np.zeros((8,5,6,8,9)) # return a new array of a given shape and type Esto tiene 5 dimensiones.
zero_array

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          ...,
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 

In [3]:
# numpy.arange() --> Return evenly spaced values within a given interval.

array_range = np.arange(8)
array_range

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
# numpy.ones() --> Return a new array of given shape and type, filled with ones.

ones_array = np.ones((8,))
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# numpy.zeros() --> Return a new array of given shape and type, filled with zeros.

zeros_array = np.zeros((8,))
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
d1_array = np.arange(12)
d1_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
d2_array = d1_array.reshape((3,4))
d2_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
d3_array = np.zeros((3,3,3)) # + 10
d3_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
dn_array = np.arange(12).reshape((1, 2, 1, 6, 1))
dn_array

array([[[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]]],


        [[[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10],
          [11]]]]])

In [10]:
dn_array[0,1,0,0,0]

6

In [12]:
# Slicing (3,3); en el slincing de matrices, el primer rango asigna las filas, el segundo a las columnas.

slicing_array_3_3= np.ones((3,3)) # Hayq eu cogerlo como tuplas
slicing_array_3_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
slice_array=slicing_array_3_3[:2,1:]
print(slice_array)
slice_array.shape

[[1. 1.]
 [1. 1.]]


(2, 2)

In [18]:
#Slicing deep dive
lst_lst = [[i+j for j in range(6)] for i in range(0,60,10)]
print(lst_lst)
a=np.array(lst_lst)
print(a)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [19]:
verdes = a[(0,1,2,3,4),(1,2,3,4,5)]
verdes

array([ 1, 12, 23, 34, 45])

In [20]:
azules = a[3:, [0,2,5]]
azules

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [21]:
azules.shape

(3, 3)

In [22]:
mask= np.array([1,0,1,0,0,1], dtype=bool)
rojos =a[mask,2]
rojos

array([ 2, 22, 52])